name: Setup
description: Setup Java and Gradle dependencies
inputs:
  github_token:
    description: 'GITHUB_TOKEN '
    required: true
  gpg_signing_key:
    description: 'GPG_SIGNING_KEY for sonatype deploymeny'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Git Identity
      run: |
        git config --global user.name 'frontegg'
        git config --global user.email 'frontegg@users.noreply.github.com'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      if: ${{ inputs.gpg_signing_key == '' }}
      with:
        java-version: 17
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        distribution: temurin

    - name: Setup JDK 17 with Credentials
      if: ${{ inputs.gpg_signing_key != '' }}
      uses: actions/setup-java@v3
      with:
        java-version: 17
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        server-id: ossrh
        server-username: NEXUS_USERNAME
        server-password: NEXUS_PASSWORD
        gpg-private-key: ${{ inputs.gpg_signing_key }}
        gpg-passphrase: GPG_PASSPHRASE
        cache: 'gradle'
        distribution: temurin

    - name: Gradle cache
      uses: gradle/gradle-build-action@v2

